version: "3.7"
services:
    devrev:
        container_name: devrev-backend-prod
        build: 
            context: .
            dockerfile: dockerfile-prod
        image: devrev-backend-prod:latest
        env_file:
            - .env
        restart: always
        ports:
            - 3000:3000