FROM node:18-alpine
WORKDIR /home/node/app
RUN chown -R node:node /home/node/app
USER node
# COPY --chown=node:node package*.json ./
# ENV PORT=3000
# RUN npm install
# COPY --chown=node:node . .
EXPOSE $PORT
CMD ["npm", "start"]